[package]
edition = "2021"
name = "classnames-rs"
version = "0.1.0"
documentation = "https://docs.rs/classnames-rs"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = {version = "2.0", features = ["full", "extra-traits"]}

[lib]
proc-macro = true
